# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentTeam < Formula
  desc "AI team role manager — git worktrees + terminal multiplexer"
  homepage "https://github.com/JsonLee12138/agent-team"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JsonLee12138/agent-team/releases/download/v0.5.0/agent-team_darwin_amd64.tar.gz"
      sha256 "5fd553f3137fc5d7838663db2deb6a8fb7fee17337658c95ff24c3cb9a09c13b"

      define_method(:install) do
        bin.install "agent-team"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JsonLee12138/agent-team/releases/download/v0.5.0/agent-team_darwin_arm64.tar.gz"
      sha256 "6f686c1055892a8cec6fe023a045b8c36d67c13d6cf64f70866952fa9d660c6a"

      define_method(:install) do
        bin.install "agent-team"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JsonLee12138/agent-team/releases/download/v0.5.0/agent-team_linux_amd64.tar.gz"
      sha256 "6576fb0a1d24d8c0cd37ec64eb612285a11cf982bd11503f89c2513b8aaaeea7"
      define_method(:install) do
        bin.install "agent-team"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JsonLee12138/agent-team/releases/download/v0.5.0/agent-team_linux_arm64.tar.gz"
      sha256 "40a75e284c314833f4a920921f40aa40578902af98e7aacac7fcd175885b03c1"
      define_method(:install) do
        bin.install "agent-team"
      end
    end
  end
end
