# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentTeam < Formula
  desc "AI team role manager — git worktrees + terminal multiplexer"
  homepage "https://github.com/JsonLee12138/agent-team"
  version "1.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JsonLee12138/agent-team/releases/download/v1.6.1/agent-team_darwin_amd64.tar.gz"
      sha256 "60e4e2368ed43401003ff88a8b604753a0d64a9b51622c87525d277d5375313a"

      define_method(:install) do
        bin.install "agent-team"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JsonLee12138/agent-team/releases/download/v1.6.1/agent-team_darwin_arm64.tar.gz"
      sha256 "4b012e21b4240a4e95d9a5b0081cb270aac180d2f456d07da73c4f5188c7c79c"

      define_method(:install) do
        bin.install "agent-team"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JsonLee12138/agent-team/releases/download/v1.6.1/agent-team_linux_amd64.tar.gz"
      sha256 "a229b3ebbb9ff60137c398cecbf27f264f5475ab9a0182e08c87d69d9a0dbf4a"
      define_method(:install) do
        bin.install "agent-team"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JsonLee12138/agent-team/releases/download/v1.6.1/agent-team_linux_arm64.tar.gz"
      sha256 "4edfee96b8666d45edd6105c703207087ee18a464b709f481edc121caea476df"
      define_method(:install) do
        bin.install "agent-team"
      end
    end
  end
end
