# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentTeam < Formula
  desc "AI team role manager — git worktrees + terminal multiplexer"
  homepage "https://github.com/JsonLee12138/agent-team"
  version "1.0.0-beta.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JsonLee12138/agent-team/releases/download/v1.0.0-beta.0/agent-team_darwin_amd64.tar.gz"
      sha256 "55b7401fb296257ab27c1f770bd2330d8f9db8a80a9b88fa74a0e3fba42ad0b5"

      define_method(:install) do
        bin.install "agent-team"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JsonLee12138/agent-team/releases/download/v1.0.0-beta.0/agent-team_darwin_arm64.tar.gz"
      sha256 "b9412f0ebe2654fabbd98434701fbcc96c56de18c77d968e09f936f706e5551d"

      define_method(:install) do
        bin.install "agent-team"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JsonLee12138/agent-team/releases/download/v1.0.0-beta.0/agent-team_linux_amd64.tar.gz"
      sha256 "c27fcf700d03d39548ff897483252d15a59b6e1dcd5426828a8aa8bc002bd944"
      define_method(:install) do
        bin.install "agent-team"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JsonLee12138/agent-team/releases/download/v1.0.0-beta.0/agent-team_linux_arm64.tar.gz"
      sha256 "ccc16db204d2c90b4c2731c927d2575aba51f9238a1c4fc3600fb31a879a5252"
      define_method(:install) do
        bin.install "agent-team"
      end
    end
  end
end
